tap "cenkalti/rain"
brew "coreutils"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "gnupg"
brew "hledger"
brew "neovim"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "cenkalti/rain/rain", trusted: true
cask "firefox"
cask "iina"
