#!/usr/bin/env bash

cwd=`pwd`

echo ' [*] Setting up dotfiles ...'

echo ' [*] user bin directory ...'
mkdir -p ~/.local
ln -s $cwd/bin ~/.local/bin

echo ' [*] bash ...'
ln -s $cwd/bash/bashrc ~/.bashrc

echo ' [*] git ...'
ln -s $cwd/git/gitconfig ~/.gitconfig
ln -s $cwd/git/gitignore ~/.gitignore

echo ' [*] gnupg ...'
mkdir -p ~/.gnupg
ln -s $cwd/gnupg/gpg-agent.conf ~/.gnupg/gpg-agent.conf

echo ' [*] python ...'
mkdir -p ~/.pip
ln -s $cwd/python/pip.conf ~/.pip/pip.conf

echo ' [*] readline ...'
ln -s $cwd/readline/inputrc ~/.inputrc

echo ' [*] ruby ...'
ln -s $cwd/ruby/gemrc ~/.gemrc
ln -s $cwd/ruby/irbrc ~/.irbrc
mkdir -p ~/.bundle
ln -s $cwd/ruby/bundler-config ~/.bundle/config

echo ' [*] tmux ...'
ln -s $cwd/tmux/tmux.conf ~/.tmux.conf

echo ' [*] vim ...'
ln -s $cwd/vim/vimrc ~/.vimrc

echo ' [*] x ...'
ln -s $cwd/x/Xresources ~/.Xresources
ln -s $cwd/x/xinitrc ~/.xinitrc
mkdir -p ~/.config/i3
ln -s $cwd/x/i3-config ~/.config/i3/config

echo ' [*] Setup completed!'
