#!/usr/bin/env bash

# Full path of script
cwd="$(dirname "$(grealpath "$0")")"

# Commands
log='echo'
create='mkdir -p'
link='ln -sfh'

# Start setup
$log 'Setting up dotfiles ...'

$log '  bash'
$link "$cwd/bash/bash_profile" "$HOME/.bash_profile"

$log '  bin directory'
$create "$HOME/.local"
$link "$cwd/bin" "$HOME/.local/bin"

$log '  git'
$create "$HOME/.config/git"
$link "$cwd/git/config" "$HOME/.config/git/config"
$link "$cwd/git/ignore" "$HOME/.config/git/ignore"

$log '  gnupg'
$create "$HOME/.gnupg"
$link "$cwd/gnupg/gpg-agent.conf" "$HOME/.gnupg/gpg-agent.conf"

$log '  readline'
$link "$cwd/readline/inputrc" "$HOME/.inputrc"

$log '  tmux'
$link "$cwd/tmux/tmux.conf" "$HOME/.tmux.conf"

$log '  vim'
$link "$cwd/vim/vimrc" "$HOME/.vimrc"

$log 'Done.'
