#!/usr/bin/env bash

if ! command -v realpath &> /dev/null; then
  echo "Please install coreutils package for realpath command."
  exit 1
fi

# Full path of script
readonly CWD="$(dirname "$(realpath "$0")")"

# Commands
_log() {
  echo "$1"
}

_create() {
  mkdir -p "$1"
}

_link() {
  ln -sfn "$1" "$2"
}

# Start setup
_log 'Setting up dotfiles ...'

_log '  alacritty'
_create "$HOME/.config/alacritty"
_link "$CWD/alacritty/alacritty.yml" "$HOME/.config/alacritty/alacritty.yml"

_log '  bin directory'
_create "$HOME/.local"
_link "$CWD/bin" "$HOME/.local/bin"

_log '  gh'
_create "$HOME/.config/gh"
_link "$CWD/gh/config.yml" "$HOME/.config/gh/config.yml"

_log '  git'
_create "$HOME/.config/git"
_link "$CWD/git/config" "$HOME/.config/git/config"
_link "$CWD/git/ignore" "$HOME/.config/git/ignore"

_log '  gnupg'
_create "$HOME/.gnupg"
_link "$CWD/gnupg/gpg.conf" "$HOME/.gnupg/gpg.conf"

_log '  gnupg gpg-agent'
_create "$HOME/.gnupg"
_link "$CWD/gnupg/gpg-agent.conf" "$HOME/.gnupg/gpg-agent.conf"

_log '  python pip'
_create "$HOME/.config/pip"
_link "$CWD/python/pip.conf" "$HOME/.config/pip/pip.conf"

_log '  readline'
_link "$CWD/readline/inputrc" "$HOME/.inputrc"

_log '  ruby'
_link "$CWD/ruby/gemrc" "$HOME/.gemrc"
_link "$CWD/ruby/irbrc" "$HOME/.irbrc"

_log '  ruby bundler'
_create "$HOME/.bundle"
_link "$CWD/ruby/bundler-config" "$HOME/.bundle/config"

_log '  ssh'
_create "$HOME/.ssh"
_link "$CWD/ssh/config" "$HOME/.ssh/config"

_log '  tmux'
_link "$CWD/tmux/tmux.conf" "$HOME/.tmux.conf"

_log '  vim'
_link "$CWD/vim/vimrc" "$HOME/.vimrc"

_log '  zsh'
_link "$CWD/zsh/zshenv" "$HOME/.zshenv"
_link "$CWD/zsh/zshrc" "$HOME/.zshrc"

_log 'Done.'
