xrdb -merge ~/.Xresources

! Keyboard
! Caps lock to Escape
setxkbmap -option caps:escape

! Typematic delay and rate
xset r rate 200 30

! Trackpad
! Tapping Enabled
xinput set-prop --type=int --format=8 bcm5974 'libinput Tapping Enabled' 1

! Natural Scrolling Enabled
xinput set-prop --type=int --format=8 bcm5974 'libinput Natural Scrolling Enabled' 1

! Input method modules
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

! Start fcitx
fcitx-autostart &

! Start i3 window manager
exec i3
