# Skip adding duplicate command lines to history
setopt histignoredups
# Write to history file incrementally
setopt incappendhistory

# Use vi key binding
bindkey -v
# Emacs-style search
bindkey ^R history-incremental-search-backward

# Reduce zsh key timeout
export KEYTIMEOUT=1

# Shell prompt
export PS1='%~ %# '

# Set locale
export LANG=en_GB.UTF-8
export LC_ALL=en_GB.UTF-8

# Standard programs
export EDITOR=vim
export PAGER=less

# fzf include hidden files and exclude certain directories
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'

# docker-machine
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="$HOME/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"

# Homebrew
export HOMEBREW_NO_AUTO_UPDATE=1

# Reset PATH
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
# Use coreutils
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
# Use Homebrew-installed ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"
# Include Homebrew-installed ruby gem executables
export PATH="/usr/local/lib/ruby/gems/2.7.0/bin:$PATH"
# Include user-installed python packages
export PATH="$HOME/Library/Python/3.9/bin:$PATH"
# Include $HOME/.local/bin
export PATH="$HOME/.local/bin:$PATH"

# Include additional user command completion functions
fpath=($HOME/.local/share/zsh/site-functions $fpath)

# gpg-agent tty
GPG_TTY=$(tty)
export GPG_TTY

# Aliases
alias g='git'
alias ll='ls -alv --group-directories-first'
alias pig='ping google.com'

# Functions
function gi() { curl -sLw "\n" https://www.toptal.com/developers/gitignore/api/$@ ;}

# Load completion
autoload -Uz compinit
compinit
