# Shell prompt
export PS1='%~ %# '

# Set locale
export LC_ALL=en_US.UTF-8
#
# Standard programs
export EDITOR=vim
export PAGER=less
export BROWSER=open

# fzf include hidden files and exclude certain directories
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'

# Include local bin directory in PATH
export PATH="$HOME/.local/bin:$PATH"
# Use coreutils
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
# Use user-installed ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"

# gpg-agent tty
GPG_TTY=$(tty)
export GPG_TTY

# Aliases
alias g='hub'
alias ll='ls -alv --group-directories-first'
alias pig='ping google.com'

# Load completion
autoload -Uz compinit
compinit
