# Skip adding duplicate command lines to history
setopt HIST_IGNORE_DUPS
# Write to history file incrementally
setopt INC_APPEND_HISTORY

# Use vi key binding
bindkey -v
# Emacs-style search
bindkey ^R history-incremental-search-backward

# Reduce zsh key timeout
export KEYTIMEOUT=1

# Shell prompt
export PS1='%~ %# '

# Set locale
export LANG=en_GB.UTF-8
export LC_ALL=en_GB.UTF-8

# Standard programs
export EDITOR=vim
export PAGER=less
export BROWSER=/Applications/Firefox.app/Contents/MacOS/firefox

# fzf include hidden files and exclude certain directories
export FZF_DEFAULT_COMMAND='fd --type f --hidden --exclude .git'

# Homebrew
export HOMEBREW_CLEANUP_MAX_AGE_DAYS=0
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";

# Reset PATH
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/opt/homebrew/sbin:/usr/local/sbin:/usr/sbin:/sbin"
# Include $HOME/.local/bin
export PATH="$HOME/.local/bin:$PATH"
# Python
export PATH="$HOME/Library/Python/3.9/bin:$PATH"
# Ruby
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
# PostgreSQL 15
export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"

# gpg-agent tty
GPG_TTY=$(tty)
export GPG_TTY

# Aliases
alias g='git'
alias k='kubectl'
alias ll='gls -alv --group-directories-first'
alias nw='newsboat'
alias pig='ping google.com'

# Functions
function gi() { curl -sLw "\n" https://www.toptal.com/developers/gitignore/api/$@ ;}

# Include additional user command completion functions
fpath=($HOME/.local/share/zsh/site-functions $fpath)

# Load completion
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit

# Completion for AWS CLI
complete -C "$(which aws_completer)" aws
