#
# ~/.bash_profile
#

#
# Environment variable
#
## Editor
export EDITOR=vim

## Pager
export PAGER=less

## Terminal
export TERMINAL=urxvt

## fzf include hidden files and exclude certain directories
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'

## SSH agent
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

## Disable history files
export LESSHISTFILE=-
export NODE_REPL_HISTORY=""
export PSQL_HISTORY=/dev/null

## user home bin
export PATH="$HOME/.local/bin:$PATH"

#
# Source bashrc
#
[[ -f "$HOME/.bashrc" ]] && . "$HOME/.bashrc"
