#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

#
# Shell prompt
#
PS1='\n\w\n$ '

#
# Environment variable
#
## gpg
GPG_TTY=$(tty)
export GPG_TTY

#
# Alias
#
alias be='bundle exec'
alias clip='xclip -selection c'
alias g='hub'
alias ll='ls -alv --group-directories-first'
alias ls='ls --color=never'
alias ns='sudo netctl start'
alias pig='ping google.com'
