#
# ~/.bash_profile
#

# Append to history file when shell exits
shopt -s histappend

# Restrictive umask
umask 077

# Standard programs
export EDITOR=vim
export PAGER=less
export TERMINAL=xterm
export BROWSER=firefox

# Increase bash history saves
export HISTSIZE=5000
# Ignore bash history duplicates
export HISTCONTROL=ignoredups:erasedups

# SSH agent
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

# fzf include hidden files and exclude certain directories
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'

# GTK DPI scaling
export GDK_SCALE=2

# Input method framework
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

# Include local bin directory in PATH
export PATH="$HOME/.local/bin:$PATH"

# Source bashrc
[[ -f "$HOME/.bashrc" ]] && . "$HOME/.bashrc"
