#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

#
# Shell prompt
#
PS1="\n\w\n"

#
# Environment variable
#
## gpg
export GPG_TTY=$(tty)

#
# Alias
#
alias ls='ls --color=auto'
alias ll='ls -alv --group-directories-first'
alias pig='ping google.com'
alias ns='netctl start'
alias nst='netctl stop'
alias be='bundle exec'
alias g='hub'
alias xclip='xclip -selection c'
alias zz='i3lock -e && xset dpms force off'

#
# Tab completion
#
## completion for `g' alias
_completion_loader hub
complete -o bashdefault -o default -o nospace -F _git g

#
# Chruby
#
[ -n "$BASH_VERSION" ] || [ -n "$ZSH_VERSION" ] || return
source /usr/share/chruby/chruby.sh
source /usr/share/chruby/auto.sh

#
# Activate or deactivate n
#
n-set () {
  PATH="$N_PREFIX/bin:$PATH"
}

n-unset () {
  PATH="${PATH//$N_PREFIX\/bin:/}"
  hash -r
}

#
# Activate or deactivate p
#
p-set () {
  PATH="$P_PREFIX/p/versions/bin:$PATH"
}

p-unset () {
  PATH="${PATH//$P_PREFIX\/p\/versions\/bin:/}"
  hash -r
}
