#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

#
# Shell prompt
#
PS1='\n\w\n$ '

#
# Environment variable
#
## gpg
GPG_TTY=$(tty)
export GPG_TTY

#
# Alias
#
alias be='bundle exec'
alias g='hub'
alias hdev='ssh-add $HOME/.ssh/dev'
alias ll='ls -alv --group-directories-first'
alias ls='ls --color=never'
alias ns='sudo netctl start'
alias pig='ping google.com'
alias xclip='xclip -selection c'

#
# asdf
#
# Activate or deactivate asdf based on the presence of
# .tool-versions file. Guard is added to prevent unnecessary
# activation and deactivation, if asdf is already activated
# or deactivated respectively.
_ASDF_ACTIVE=0

_asdf_auto () {
  if [ -f "$PWD/.tool-versions" ]
  then
    [ $_ASDF_ACTIVE -eq 1 ] && return

    # shellcheck source=/dev/null
    . "$HOME/.asdf/asdf.sh"
    # shellcheck source=/dev/null
    . "$HOME/.asdf/completions/asdf.bash"

    _ASDF_ACTIVE=1
  else
    [ $_ASDF_ACTIVE -eq 0 ] && return

    PATH="${PATH//$HOME\/.asdf\/bin:/}"
    PATH="${PATH//$HOME\/.asdf\/shims:/}"
    complete -r asdf
    hash -r

    _ASDF_ACTIVE=0
  fi
}

# Trigger asdf activation or otherwise after command execution
trap '[ "$BASH_COMMAND" = "$PROMPT_COMMAND" ] && _asdf_auto' DEBUG
