#
# ~/.bash_profile
#

#
# Environment variable
#
## Global editor
export EDITOR=vim

## ls colors
export LS_COLORS='rs=0:ex=00;32'

## fzf include hidden files and exclude certain directories
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'

## SSH agent
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

## user home bin
export PATH="$HOME/.local/bin:$PATH"

#
# Source bashrc
#
[[ -f "$HOME/.bashrc" ]] && . "$HOME/.bashrc"
